github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/youtube-downloader",
"https://serp.co/products/youtube-video-downloader",
"https://store.serp.co/product-details/product/youtube-downloader",
]
